export interface APISpells {
    index:string;
    name:string;
    desc:string;
    higher_level:string;
    range:string;
    components:string;
    material:string;
    ritual:string;
    duration:string;
    concentration:string;
    casting_Time:string;
    level:string;
    attack_type:string;
    damage:string;
    school:string;
    classes:string;
    subclasses:string;
    url:string;
}